// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: customers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllCustomers = `-- name: GetAllCustomers :many
SELECT d.dealer,
       c.name,
       c.state,
       c.pfleet_acct_id,
       c.status,
       c.truck_qty,
       c.fleet_support_rep,
       c.field_service_rep,
       c.field_service_rep_email
FROM customers c
         INNER JOIN dealers d ON c.dealer = d.id
`

type GetAllCustomersRow struct {
	Dealer               string          `json:"dealer"`
	Name                 string          `json:"name"`
	State                string          `json:"state"`
	PfleetAcctID         pgtype.Text     `json:"pfleet_acct_id"`
	Status               NullFleetStatus `json:"status"`
	TruckQty             int16           `json:"truck_qty"`
	FleetSupportRep      string          `json:"fleet_support_rep"`
	FieldServiceRep      pgtype.Text     `json:"field_service_rep"`
	FieldServiceRepEmail pgtype.Text     `json:"field_service_rep_email"`
}

func (q *Queries) GetAllCustomers(ctx context.Context) ([]GetAllCustomersRow, error) {
	rows, err := q.db.Query(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCustomersRow
	for rows.Next() {
		var i GetAllCustomersRow
		if err := rows.Scan(
			&i.Dealer,
			&i.Name,
			&i.State,
			&i.PfleetAcctID,
			&i.Status,
			&i.TruckQty,
			&i.FleetSupportRep,
			&i.FieldServiceRep,
			&i.FieldServiceRepEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
